[package]
name = "server_core"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.8"
axum-server = "0.8.0"
rustls-acme = { version = "0.15.1", features = ["axum"] }
tokio = { version = "1.51.1", features = ["rt-multi-thread", "macros", "net", "io-util", "sync", "time"] }
futures-util = "0.3"
clap = { version = "4.6.0", features = ["derive"] }
tracing = "0.1.44"
